// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEP11EBv1hWM_iqqwxBD6fVHDUScfWdDw',
    appId: '1:245588081103:web:cf9f735b7cb9f6d460faba',
    messagingSenderId: '245588081103',
    projectId: 'unihub-9b45f',
    authDomain: 'unihub-9b45f.firebaseapp.com',
    storageBucket: 'unihub-9b45f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRT2vZt0GovvvU_ca_SyzCXsv_nZKhuds',
    appId: '1:245588081103:android:f95196e6cdc593ec60faba',
    messagingSenderId: '245588081103',
    projectId: 'unihub-9b45f',
    storageBucket: 'unihub-9b45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKnMktHVvXutWZu4OSUk0jWdGJ_qFbl9o',
    appId: '1:245588081103:ios:2014d07f65194fec60faba',
    messagingSenderId: '245588081103',
    projectId: 'unihub-9b45f',
    storageBucket: 'unihub-9b45f.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKnMktHVvXutWZu4OSUk0jWdGJ_qFbl9o',
    appId: '1:245588081103:ios:2014d07f65194fec60faba',
    messagingSenderId: '245588081103',
    projectId: 'unihub-9b45f',
    storageBucket: 'unihub-9b45f.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEP11EBv1hWM_iqqwxBD6fVHDUScfWdDw',
    appId: '1:245588081103:web:9b8fb72c55d61d8b60faba',
    messagingSenderId: '245588081103',
    projectId: 'unihub-9b45f',
    authDomain: 'unihub-9b45f.firebaseapp.com',
    storageBucket: 'unihub-9b45f.firebasestorage.app',
  );

}